"""
Django settings for tutti project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Import os to handle environment variables
import dj_database_url # Import dj_database_url to handle database URLs when deploying on Render.com
from dotenv import load_dotenv # Import load_dotenv to load environment variables from a .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))  # Load environment variables from a .env file if present



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') # Get the secret key from environment variable for security
#initially it was just her but then safe practices are to keep environmental keys ignored,, so i moved it to .env then to .gitignore so that is is not exposed when commited

# SECURITY WARNING: don't run with debug turned on in production!
# If the 'RENDER' environment variable exists, Debug is False (Secure).
DEBUG = 'RENDER' not in os.environ # Debug is True if RENDER variable is absent (i.e., in local development)
#initially debug was set to be true in order to display error messages when the server crashes but now after deployment it will only display a starndard error 404 page


# Allow the app to run on Render's URL
ALLOWED_HOSTS = ['*'] # In production, specify your domain names here for security. 
#initially it was just "ALLOWED_HOSTS = []" but then after wanting to deploy it, we include the '*'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tuttiapp', #this is our app within the project folder. we created it using the command "django-admin startapp tuttiapp"
    'django_daraja', #we install this here after doing the "pip install django_daraja" which now allows the mpesa stk push integration
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For serving static files on Render.com. i have added it later in deployment stages of the project . INITIALLY IT WAS NOT THERE
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tutti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Look for the DATABASE_URL environment variable,
        # otherwise fall back to local SQLite
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
} # i have changed this database configuration to use dj_database_url for easier deployment on Render.com
#this has been done in the late stages of deployment of the project. Normally there is a predefined way that the databases behave


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/' #defaul ie it existed



#added this
STATIC_URL = '/static/'
# This creates a folder called 'staticfiles' where Render will look for CSS
STATIC_ROOT = os.path.join(BASE_DIR, 'tuttiapp/static')
# This tells Django to use Whitenoise to store files
#(Forgiving - works even if files are missing)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'tuttiapp.User'  #Allows us to use custom user model defined in tuttiapp/models.py instead of default Django User model
#originally it was not there, so i added it to tell django to use my parameters when defining the user



# Where to go after logging in (The Dashboard)
LOGIN_REDIRECT_URL = 'dashboard'
#originally it was not there so i added it to avoid going to the admin page after logging in but rather, it redirects back to the dashboard



# Where to go after logging out (The Login Page)
LOGOUT_REDIRECT_URL = 'login'
#redirects the program where to go after loggin out, instead of going to the admin page, it just goes to the login page



load_dotenv()  # take environment variables from .env.file. These variables are the once we defined then since we want to avoid exposing then we .gitignore the .env file
# M-Pesa Configuration (Sandbox)
MPESA_ENVIRONMENT = os.getenv('MPESA_ENVIRONMENT')  # 'sandbox' or 'production'
MPESA_CONSUMER_KEY = os.getenv('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = os.getenv('MPESA_CONSUMER_SECRET')
# Default Sandbox Credentials (Do not change these for testing)
MPESA_SHORTCODE = os.getenv('MPESA_SHORTCODE')
MPESA_PASSKEY = os.getenv('MPESA_PASSKEY')
MPESA_EXPRESS_SHORTCODE = os.getenv('MPESA_EXPRESS_SHORTCODE')
MPESA_SHORTCODE_TYPE = os.getenv('MPESA_SHORTCODE_TYPE')
