# Generated by Django 5.2.9 on 2025-12-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuttiapp', '0002_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('RESCHEDULE_PENDING', 'Reschedule Pending'), ('COMPLETED', 'Completed'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
